krokedil/klarna-checkout-for-woocommerce

- includes/class-klarna-checkout-for-woocommerce-api-callbacks.php
- includes/class-klarna-checkout-for-woocommerce-order-lines.php
We're changing how we add prices to the order when creating an order in WooCommerce via the push notification from Klarna (currently used for backup order creation if something goes wrong during standard checkout process in frontend).
With this update products, fees & shipping are added with the price returned from the Klarna order. Previously we have added the price by getting it from the product object in Woocommerce. This caused issues with stores running multi currency plugins.
Future improvements to make this function even more stable would be the following:
- Improve support for handling store credits.
- Add product item meta data in order data sent to Klarna. So we can retrieve it and add it to the order in Woo.
- Calculate coupons so that the original price and the discounted …
> Backup order creation rewrite

- includes/class-klarna-checkout-for-woocommerce-api.php
I got an empty error message "An error occurred during communication with Klarna ().", with this change, at least I get "An error occurred during communication with Klarna (403 Forbidden)."
> Add response code / status message in case error message is empty

- includes/class-klarna-checkout-for-woocommerce-api.php
Get billing countries uses the WC function: get_allowed_countries which returns all the countries that the store sells to. #226
> Added billing countries field

- includes/class-klarna-checkout-for-woocommerce-templates.php
"Failed to load Klarna Checkout template file" error will not be rendered if the action "woocommerce_cart_has_errors" ran. #230
> Fix for navigating to checkout with a product out of stock

- includes/class-klarna-checkout-for-woocommerce-merchant-urls.php
Instead of using get_home_url() . '/our-url/' use the home_url('/our-url/') to prevent dubble dashes.
I first saw this when we used WPML with a base catalog on the default language. Our merchant urls becomes like this:
https://our-site.com/sv//wc-api/KCO_WC_Push/?kco-action=push&kco_wc_order_id={checkout.order.id}&kco_session_id=1
I also added some standard wp-filters.
> Bugg fix for home_url on merchant urls

- includes/class-klarna-checkout-for-woocommerce-api.php
- includes/class-klarna-checkout-for-woocommerce-order-lines-from-order.php
* Order tax amount is now getting the correct value when a bulk subscription renewal is triggered.
> Fix for incorrect order_tax_amount when making bulk renewal requests

- classes/class-kco-api.php
- classes/requests/checkout/post/class-kco-request-update.php
- includes/kco-functions.php
This was due to how we handled the need to not update an order. This should never happen on a page load.
> Fix for incorrect order id being saved to order.

- classes/requests/checkout/post/class-kco-request-update.php
We have come across a bug in Klarna Checkout for WooCommerce. This has to do with the combination of virtual & non-virtual products in cart.
Here are the step that allow us to replicate this issue:
1. Add virtual product(No Shipping) to cart
2. Open checkout page(optional). Works normally without issue on a fresh cart.
3. Add 1 physical product on cart
4. Open the checkout page
5. Remove physical product from cart
6. Open Checkout page
When we do step 3/4, WooCommerce updates the order at Klarna and adds a shipping option. However, when we do step 5, the shipping information for the order is not removed from Klarna. Since the KCO widget reads order from Klarna and find it out of sync with the local WooCommerce cart(no shipping), it goes into some sort of infinite loop.
Klarna Doc about …
> Clear shipping information on Klarna when the order has no shipping

- assets/js/klarna-checkout-for-woocommerce.js
Sometimes the "no shipping available" message is enclosed in HTML tags (e.g., for adding the `woocommerce-error` class), and sometimes it is plain text.
> Print the "no shipping available" message as HTML

- classes/class-kco-api-callbacks.php
Mirror the behavior in kco_confirm_klarna_order.
> Run the custom payment_complete hook on callback

- classes/class-kco-checkout.php
Currently the plugin has a bug when a coupon that gives 100% discount (and free shipping) is used in checkout page. When the coupon is added and cart total results in 0, KCO is still displayed. This is not the intended behavior.
This commit adds a check in `woocommerce_after_calculate_totals`. If the cart doesn't need payment, we now set the session `WC()->session->reload_checkout` to true. WooCommerce will then automatically reload the checkout page and the KCO payment method template will no longer be used (and KCO will not be an available payment method).
> Reload checkout page if cart doesn't need payment during update request

- classes/class-kco-gateway.php
- classes/requests/checkout/post/class-kco-request-create.php
- classes/requests/checkout/post/class-kco-request-update.php
External payment methods ("EPM") are not available in pay for order.
This fixes the issue with EPM not being available on the embedded checkout page since the `order_id` is also not available there until after the customer has placed an order.
> Develop epm p4o

- classes/class-kco-subscription.php
The current filter is insufficient since it cannot find any subscriptions. When we then attempt to save the recurring token, there is no subscriptions to add it do.
> Fix issue with subscription not found

- includes/kco-functions.php
This function was defined 5 years ago, and is never used.
> Remove unused function

- classes/requests/checkout/post/class-kco-request-create.php
- classes/requests/checkout/post/class-kco-request-update.php
B2B is only prefilled if B2B is the default customer type. If you switch to B2B, Klarna will ignore the company information in the update request.
> Prefill company user data if available

- classes/requests/helpers/class-kco-request-order.php
`reset` wants a reference, not a function expression.
We assume that `get_shipping_methods` never returns an empty array (that would crash `reset` too).
> Fix passed by reference warning

- classes/requests/helpers/class-kco-request-order.php
There is no need to multiply `$max_order_line_amount` by 100 as unlike `$fee_total_amount` it is not divided by 10000.
> Fix total amount comparison for negative subscription fees

- classes/requests/helpers/class-kco-request-options.php
The `$checkout_flow` variable is referenced by not defined in the context of the method.
> Fix undefined $checkout_flow variable.

- assets/js/klarna-checkout-for-woocommerce.js
Make use of the [MutationObserver API](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) to check for changes to the DOM (when the modal disappear) instead of using timers.
> Scroll to WC notice on checkout error

- classes/class-kco-gateway.php
Klarna seems to have made a change that causes the response body to be empty when making this call. So we can not expect a body to be returned to us.
> Dont fail upsell if response is empty

- includes/kco-functions.php
Wrong $order->set_status( 'canceled', ' ', ' ' ); in klarna-checkout-for-woocommerce/includes/kco-functions.php
Fixed that status according issue no #517
> Fixed issue no #517 - Typo mistake in  object (set_status function)

- classes/class-kco-api-callbacks.php
- classes/class-kco-api.php
- classes/class-kco-confirmation.php
- classes/class-kco-gateway.php
- classes/class-kco-subscription.php
- classes/requests/checkout/post/class-kco-request-create.php
- includes/kco-functions.php
- klarna-checkout-for-woocommerce.php
As described in the [recipe book](https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book):
- `get_post( $post_id )` → `wc_get_order( $post_id )`
- `update_post_meta` → `WC_Order::update_meta_data`
- `add_post_meta` → `WC_Order::add_meta_data`
- `delete_post_meta` → `WC_Order::delete_meta_data`
Furthermore, where applicable, if a method is available for the meta field, that will be used in favor of retrieving it through the meta data function.  For example,  
```
get_post_meta($order_id, '_transaction_id', true)
```
is replaced with 
```
WC_Order::get_transaction_id()
```
If a meta data function is available, and update_meta_data is still used for that meta data, WooCommerce will warn about directly modifying internal meta data.
Note:
1. The …
> Add HPOS compatibility

- assets/js/klarna-checkout-for-woocommerce.js
I suspect we receive `data = false` if the AJAX request succeeds, but the result is a failure. In other instances, we receive `data = bad_nonce`. This change should cover both cases.
> Check for retrieval only if data is an object or array

- classes/class-kco-api-callbacks.php
- classes/class-kco-api.php
- classes/class-kco-confirmation.php
- includes/kco-functions.php
Fixes #544
Also moves the logic for the validation of this to a single function, to not split functionality between different functions. Adds a verification that the order actually has the same metadata value stored in the order before we return it.
> Fix issue with how we make meta queries when looking up orders

- classes/class-kco-subscription.php
- The recurring token was written incorrectly to the parent order instead of the subscription.
- If the recurring token cannot be found in the subscription, it is retrieved from the parent order.
- The recurring token show now be displayed on the subscription page as expected.
Related task: https://app.clickup.com/t/865cq7zku
> Recurring token not shown on the subscription page

- classes/class-kco-gateway.php
- `process_payment` expects an array with a result. Currently, we're simply returning `false` if the Klarna order could not be retrieved.
> process_payment expects an array with a result

- classes/class-kco-settings-saved.php
Currently, we always test both production and test credentials regardless of whether the merchant has enabled test mode or not.
- Only test productions credentials if test mode is disabled.
- Only test test credential if test mode is enabled.
- Changed the error message when a test result in an HTTP 401 error.
Related task: https://app.clickup.com/t/865ct9r69
> Test API credentials depending on the environment

- classes/class-kco-subscription.php
Add Klarna hosted payment page as allowed external url for wp_safe_redirect.
> Fix issue with redirect to HPP when changing/updating subscription payment method

- classes/class-kco-gateway.php
- classes/class-kco-subscription.php
Currently we do the following check if we should try to fetch a recurring token from Klarna:
```
if ( class_exists( 'WC_Subscription' ) && ( wcs_order_contains_subscription( $wc_order, array( 'parent', 'renewal', 'resubscribe', 'switch' ) ) || wcs_is_subscription( $wc_order ) ) ) {
}
```
In some cases it seems as this check is not true even though the customer is placing a subscription in Woo.
To improve this, we now add a meta data field during `process_payment()` where we save `_kco_recurring_order` as `yes` or `no`. We can then use this as an improved check if we should try to fetch the recurring token, like this:
```
$recurring_order = $wc_order->get_meta( '_kco_recurring_order', true );
if ( 'yes' === $recurring_order || class_exists( 'WC_Subscription' ) && ( …
```
> Improve logic when to fetch recurring token from Klarna

- assets/js/klarna-checkout-for-woocommerce.js
- classes/class-kco-gateway.php
- languages/klarna-checkout-for-woocommerce.pot
- add the customer's email address to identify the successful order in the log.
- when processing payment on the backend, add extra logging for successful and failed processing attempts.
> Add extra logging when processing order

- classes/class-kco-checkout.php
- classes/requests/helpers/class-kco-request-cart.php
Previously, we used the Cart object to retrieve the coupon, which would yield 0 in all cases when "Apply before tax" is disabled in the smart coupons settings.
> Fix smart coupons when "apply before tax" is disabled

- classes/class-kco-api-callbacks.php
`WC_Order::get_date_paid` is true if the payment has been completed which covers cases for when the order status is cancelled or refunded.
> Prevent order status change on callback once processed once

- classes/class-kco-confirmation.php
- classes/requests/checkout/post/class-kco-request-update-confirmation.php
- classes/requests/helpers/class-kco-merchant-urls.php
`wc_get_order_id_by_order_key` has terrible performance on databases with many orders when HPOS is not enabled.
- pass order ID where applicable.
> Retrieve order id through WC order

- classes/class-kco-templates.php
This concerns the issue where the template fails to load when it is not returned in the create session request as an HTML snippet, which prevents the customer from proceeding to the checkout page. This is an issue if the store offers other payment methods, since the customer won't be able to pay with those in this situation.
- if KCO is the only available gateway, notify the customer but remain on the checkout page.
- if there is an alternative gateway, switch to it and notify the customer that KCO is not available.
Related task: https://app.clickup.com/t/3wg79zp
> Handle situations when HTML snippet not available

- classes/class-kco-gateway.php
If the merchant set the default location to "No location by default", no billing country will be specified in the checkout page which affects customers whose billing country is not set in their account, and all guests. 
Usually, if the store only serves one country, WooCommerce automatically selects that country. However, the billing country won't be set until the customer provides their billing address. Given that there is only one option available to the customer, we can assume that it will be the selected country.
**This issue only affects subscriptions, since we need to check the billing country to determine whether subscriptions should be available.**
https://app.clickup.com/t/86941jdcx
> Use first country available as billing country for subscriptions

- assets/js/klarna-checkout-for-woocommerce.js
When the customer clicks on the buy button, the `validation_callback`  event will be triggered. Initially, I thought we could perform validation before we respond, but at this point, the modal is already open, and there is no event that is in-between the click event and the modal opening. Thus, we cannot prevent it from appearing. However, there is a different option: we can display the error message inside the modal (see screenshot) which is what this PR addresses.
If multiple checkout errors happens, it won't look very pretty, though.
And we cannot send any marking in the text since Klarna escapes all HTML, so we have to remove it.
task: https://app.clickup.com/t/8694jn5hy
> Display the Woo error message inside the Klarna modal

- classes/class-kco-api-callbacks.php
- includes/kco-functions.php
Task: https://app.clickup.com/t/8694t0yt2
> Validate order content

- classes/class-kco-gateway.php
If the order doesn't need shipping, the Klarna order will still have the `shipping_address` fields set to whatever is stored in the `billing_address`. However, in Woo, the shipping address fields will be empty, resulting, whenever an order doesn't shipping, in checkout errors.
Task: https://app.clickup.com/t/8694t0yt2
> Check if we need to verify shipping address

- includes/kco-functions.php
As identified in https://github.com/krokedil/klarna-checkout-for-woocommerce/pull/599, we need to loosen the comparison of the quantity fields. This can be done by without having to use `==` (instead of `===`) by converting the values to string.
Assume shipping always matches.
Task: https://app.clickup.com/t/86952c3mf
> Fix control of quantity and assume shipping always matches

- classes/class-kco-gateway.php
For the initial subscription, the Klarna order ID should always exist in the session. This also applies to (pending) renewal subscription since existing Klarna order ID is no longer valid for the renewal, we must retrieve it from the session, not the order.
https://app.clickup.com/t/8694zwhed
> Retrieve Klarna ID from session for subscription

- assets/js/klarna-checkout-for-woocommerce.js
- classes/class-kco-ajax.php
- classes/class-kco-gateway.php
Added a new action hook, `kco_customer_type_changed` which is triggered whenever the customer switches between organization and person in the checkout.
https://app.clickup.com/t/3wvez97
> Add kco_customer_type_changed action

- assets/js/klarna-checkout-for-woocommerce.js
Add check to see if errors exists before triggering scroll to errors, after Klarna order submit.
> Check for errors before triggering scroll on order submit

- classes/class-kco-fields.php
- classes/requests/helpers/class-kco-request-options.php
The setting for allowed_customer_types has been updated to now also include DE (Germany).
> Adding DE to allowed_customer_types

- includes/kco-functions.php
Skip order content validation if WooCommerce Product Bundles plugin is installed.
> Add bundle plugin check to order validation

- classes/class-kco-gateway.php
There doesn't seem to be a standard naming convention for country states. E.g., the state of Dublin in Woo is "D" (or "Dublin") whereas in Klarna it is "Co. Dublin". Furthermore, the way you enter the state in Woo is through a select dropdown, whereas in Klarna it must be typed unless autocompleted.
https://app.clickup.com/t/8695nt5cy
> Skip state validation

- classes/admin/class-klarna-for-woocommerce-addons.php
- classes/class-kco-credentials.php
- classes/class-kco-fields.php
- includes/kco-functions.php
https://app.clickup.com/t/8694w2y1z
> Address Woo Quality Insight recommendations

- .distignore
- .github/workflows/create-dev-zip.yml
With this GitHub action workflow you will be able to trigger a manual workflow to create a dev version from a specific branch of the plugin that then will be uploaded to Amazon S3 and later available through a public url for 30 days that can be shared internally or externally if needed.
> Add dev zip GitHub action

- assets/js/klarna-checkout-for-woocommerce.js
Check if no payment option is available before running KCO code on document ready in checkout.
Question 1:
Perhaps this is a bigger issue; should the JS file as a whole not be included in the checkout if no payment option is available?
Question 2:
Is `ul.wc_payment_methods` a bad target, should WooCommerce change the class name? I see that we target quite a bit of WooCommerce classes though, so this might be fine.
> Check if no payment option is available

- classes/class-kco-gateway.php
This issue only happens during the redirect flow (HPP) since we seem to save the order metadata from the CREATE request which doesn't guarantee the phone number field to exist in the response. Whereas with the embedded flow, we issue a GET request.
Response:
```
"shipping_address": {
"given_name": "Alice",
"family_name": "Test",
"email": "customer@email.se",
"street_address": "S\u00f6dra Blasieholmshamnen 2",
"postal_code": "11148",
"city": "Stockholm",
"country": "se"
},
```
This also applies to the `billing_address` field.
- check if we have a shipping phone before we attempt to access it. 
https://app.clickup.com/t/8698w4qrn
> Save shipping phone only if it exists in the Klarna response

- classes/class-kco-credentials.php
- classes/class-kco-fields.php
- classes/requests/checkout/post/class-kco-request-test-credentials.php
- classes/requests/class-kco-request.php
New merchants onboarding through Kustoms portal will have a MID that start with M in production or PM in playground.
From 13/6 2025 these new credentials will require all requests to go through the `kustom.co` domain instead of `klarna.com` following the same structure for playground and regions. In cases where merchants have special MIDs, there is also a filter added to support setting the domain manually if needed.
------
* Tweak - API Usernames that start with either M for production or PM for playground will use the `kustom.co` domain instead of `klarna.com` for all API requests. The domain can be changed using the filter `kco_api_domain` to set this manually if needed.
> Switch API domain for Kustom onboarded merchants

- classes/class-kco-api.php
- classes/class-kco-checkout.php
- classes/requests/checkout/post/class-kco-request-update.php
- classes/requests/class-kco-request.php
The `status` is not always returned in the response from Klarna.
```
Got error 'PHP message: PHP Warning:  Trying to access array offset on false in plugins/klarna-checkout-for-woocommerce/classes/class-kco-checkout.php on line 118
```
However, based on this error message, it is the `update_klarna_order` call that removes the `status`. Otherwise, the warning should have appeared [on line 112](https://github.com/krokedil/klarna-checkout-for-woocommerce/blob/develop/classes/class-kco-checkout.php#L112).
I suggest we either store the status like I've done in this PR, and only update it if it exists in the new response, or we only overwrite the `$klarna_order` if the result is non-`false`.
https://app.clickup.com/t/8698w3rbb
> Addresses PHP warning due to missing 'status'

- classes/requests/helpers/class-kco-merchant-urls.php
As of WC 10.0, the structure of the `wp_woocommerce_session_` cookie was changed to use a single pipe `|` to separate values instead of `||` like previously. This has resulted in split-by-delimiter to fail, yielding a session value that contain the entire content of the cookie instead of only the first index.
https://app.clickup.com/t/869a0dkx9
> Fix malformed kco_session_id
