includes/class-wc-klarna-banners.php
URL to new customer signup and onboarding.
=> Klarna LEAP functionality

includes/class-klarna-checkout-for-woocommerce-ajax.php, includes/class-klarna-checkout-for-woocommerce-api-callbacks.php, includes/class-klarna-checkout-for-woocommerce-api.php, includes/class-klarna-checkout-for-woocommerce-gateway.php, includes/class-klarna-checkout-for-woocommerce-order-lines.php, includes/klarna-checkout-for-woocommerce-functions.php, klarna-checkout-for-woocommerce.php
* Adds prefix kco_wc_order_id_ to transient name.
* Adds support for cart_hash control to avoid mismatch in order totals between Klarna & Woo
=> Fix check order total

.gitignore, includes/class-klarna-checkout-for-woocommerce-api-callbacks.php
* Code standards
* Exclude ds_store files in .gitignore
=> Small fixes

includes/class-klarna-checkout-for-woocommerce-api.php, includes/class-klarna-checkout-for-woocommerce-gateway.php, languages/klarna-checkout-for-woocommerce.pot
Make it possible to view KCO iframe on thankyou page even if the page is reloaded.
=> Clear sessions in woocommerce_thankyou

includes/class-klarna-checkout-for-woocommerce-api-callbacks.php, includes/class-klarna-checkout-for-woocommerce-api.php, includes/class-klarna-checkout-for-woocommerce-order-lines-from-order.php
* Recurring orders are now created correctly when having zero decimals as number of decimals.
=> Develop zero decimals subscription

includes/class-klarna-checkout-for-woocommerce-api-callbacks.php
* Added logic for saving company name to order in the fallback sequence if purchase is B2B.
=> Develop b2b backup order creation

assets/js/klarna-checkout-for-woocommerce.js, includes/class-klarna-checkout-for-woocommerce-api-callbacks.php, includes/class-klarna-checkout-for-woocommerce-api.php, includes/class-klarna-checkout-for-woocommerce-order-lines-from-order.php, includes/class-klarna-checkout-for-woocommerce-subscription.php, klarna-checkout-for-woocommerce.php, readme.txt
* Fixed issue for order_tax_amount not being set as correct amount when bulk renewal subscription is triggered.
=> Version 1.11.5

classes/class-kco-subscription.php, classes/class-kco-templates.php
If the customer had something in cart while wanted to change payment method for a subscription payed with KCO this resulted in a couple of errors (related to order_amount sent to Klarna and KCO template file handling). This is fixed in the PR.
=> Improved handling of subscription payment method change

classes/requests/helpers/class-kco-request-cart.php
This change makes it possible for other plugins to modify what's sent in cart items to Klarna.
=> Added filter kco_wc_cart_line_item

klarna-checkout-for-woocommerce.php
wp_safe_redirect seems to redirect user to /wp-admin in some cases. wp_redirect solves this.
=> Change redirect function for EPM

assets/css/klarna-checkout-admin.css, classes/admin/class-wc-klarna-banners.php
Changed playground URL to a single link.
Fixed non-standard screen issues.
=> Banner develop updated

classes/class-kco-api.php
Redirect customer to thankyou page if response to an update request is READ_ONLY_ORDER and we have an order with the current Klarna order ID.
=> Read_only error handling

readme.txt
WC required version is set to October 2020 and PHP version to match WC requirement.
=> PHP and WC requirement bump

includes/kco-functions.php
=> Do not print HTML in AJAX response on error

readme.txt
Updating links to Docs.
Removing "Specific requirements" section.
=> Update readme.txt - section and links

classes/class-kco-templates.php
=> Update incorrect template reference

classes/class-kco-fields.php
=> Inform customer of KSA tax settings

classes/class-kco-fields.php
=> Expand shipping documentation links

tests/e2e/.env, tests/e2e/cli/install.js, tests/e2e/config/tests.json, tests/e2e/helpers/orderManagement.js, tests/e2e/helpers/urls.js, tests/e2e/readme.md, tests/e2e/tests/kcoTest.spec.js
=> Dev e2e test order management

tests/e2e/helpers/iframeHandler.js
=> Handle potential warning window on checkout

includes/kco-functions.php
Refer to https://github.com/krokedil/klarna-shipping-service-for-woocommerce/pull/28
=> Pass the purchase currency onto KSS

classes/class-kco-gateway.php
=> Remove wc-cart JS dependency

classes/class-kco-confirmation.php, klarna-checkout-for-woocommerce.php, languages/klarna-checkout-for-woocommerce.pot, readme.txt
* Fix           - Resolved a critical error that occurred in certain cases when an external payment method ("EPM") was used and the order ID couldn't be retrieved.
=> Version 2.11.1

classes/class-kco-gateway.php
`selected_shipping_option` is an [optional field](https://docs.klarna.com/api/checkout/#operation/readOrderMerchant) and only available if shipping is displayed in iframe.
=> Fix undefined selected_shipping_option index

classes/class-kco-gateway.php, klarna-checkout-for-woocommerce.php, languages/klarna-checkout-for-woocommerce.pot, readme.txt
* Fix           - Fixed an issue where the recurring token was no longer being displayed in the billing fields.
* Fix           - Fixed an undefined index warning that occurred when the shipping was shown outside of the iframe.
* Fix           - When processing a payment, and the order is not found, we'll now return the response in the expected format.
=> Version 2.11.3

classes/admin/class-klarna-for-woocommerce-addons.php
Related task: https://app.clickup.com/t/865crkh62
=> Remove the "Klarna Add-ons" page.

classes/class-kco-fields.php, classes/class-kco-gateway.php, classes/class-kco-templates.php
Add a setting to redirect the customer to Klarna's hosted payment page. Requires the following filter to display the setting:
```
add_filter('kco_enable_redirected_flow', '__return_true');
```
=> Add support for the redirect flow

classes/requests/class-kco-request.php, classes/requests/helpers/class-kco-request-cart.php, classes/requests/helpers/class-kco-request-options.php
=> Class property modified without being defined

assets/js/klarna-checkout-for-woocommerce-admin.js, assets/js/klarna-checkout-for-woocommerce.js, assets/js/klarna-for-woocommerce-addons.js, klarna-checkout-for-woocommerce.php, languages/klarna-checkout-for-woocommerce.pot, package.json, readme.txt
* Fix           - Bumped the plugin version.
=> Version 2.12.1

classes/class-kco-logger.php
task: https://app.clickup.com/t/8694rxyan
=> Fix TypeError in logger expecting array receiving bool

klarna-checkout-for-woocommerce.php, languages/klarna-checkout-for-woocommerce.pot, readme.txt
* Fix           - Fixed a critical error in logging caused by a recent release of the third-party theme Avada.
=> Version 2.12.4

classes/class-kco-gateway.php
Task: https://app.clickup.com/t/8694t0xng
=> Validate the data of the checkout fields matches the Klarna order

includes/kco-functions.php
https://app.clickup.com/t/86950mxqv
=> Change to only verify the first part of the shipping method id.

includes/kco-functions.php
Task: https://app.clickup.com/t/86951qrnt
=> Increase logging for mismatch

classes/class-kco-gateway.php
Task: https://app.clickup.com/t/86950guqa
=> Use default country if billing field is not set

classes/class-kco-subscription.php
https://app.clickup.com/t/8694vg76f
=> Always show recurring field on subscription page

classes/class-kco-checkout.php
Add check to see that sessions exists before retrieving Klarna order id from it, to prevent crash on page edit of checkout.
=> Add session check to KCO_Checkout

includes/kco-functions.php
Closes #611.
https://app.clickup.com/t/8695mw7dy
=> Handle variable products as a single product

includes/kco-functions.php, klarna-checkout-for-woocommerce.php, languages/klarna-checkout-for-woocommerce.pot, readme.txt
* Fix           - Fixed an undefined array key warning.
=> Version 2.13.2

.gitignore, includes/kco-functions.php
Convert to string before comparing, similar to how we did in #600
=> Compare quantity as a string

.github/workflows/deploy.yml, .gitignore, composer.lock, klarna-checkout-for-woocommerce.php, languages/klarna-checkout-for-woocommerce.pot, package.json, readme.txt
* Fix - Added a refresh of the iframe as a checkout error is detected.
=> Version 2.13.4

classes/class-kco-ajax.php, klarna-checkout-for-woocommerce.php, package.json, readme.txt
* Fix - Limit the max size of a log message from the frontend to 1000 to prevent large logs from being created.
=> Version 2.13.5

.github/workflows/deploy.yml, composer.lock, klarna-checkout-for-woocommerce.php, package-lock.json, package.json, readme.txt
* Fix - Fixed checkout scrollTo animations that were sometimes queued multiple times, potentially causing the checkout page to freeze - Thank you Oxyc for the fix!
* Fix - Fixed an issue where KCO-related JS was loaded even when no payment option was available at checkout.
=> Version 2.13.6

classes/admin/class-wc-klarna-banners.php, composer.lock, klarna-checkout-for-woocommerce.php, languages/klarna-checkout-for-woocommerce.pot, package-lock.json, package.json, readme.txt
* Fix - Fixed a settings related issue, that in certain cases could cause a critical error on fresh plugin installs.
=> Version 2.13.7

composer.lock, klarna-checkout-for-woocommerce.php, languages/klarna-checkout-for-woocommerce.pot, package-lock.json, package.json, readme.txt
* Fix - Fixed an issue where a 'Pay for Order' button sometimes appeared on the order received page even after payment was completed.
=> Version 2.13.8

assets/js/klarna-checkout-for-woocommerce.js, classes/class-kco-gateway.php
Move the full account section, to avoid always displaying the login input fields.
=> Move the full account section

classes/class-kco-gateway.php, classes/requests/class-kco-request.php
- checks if error_messages exists before we attempt to retrieve them.
- aborts validation if Klarna order ID is missing.
https://app.clickup.com/t/8698w6vk8
=> Handles null body response

classes/admin/class-kco-admin-notices.php
Update docs URL for Optimizing your checkout when using an Iframe-based checkout.
=> Update docs URL

classes/class-kco-settings-saved.php
Remove link/text regarding Klarna Payments from API credentials notice text.
=> Remove KP link

classes/class-kco-logger.php
=> Rebrand log name

classes/class-kco-gateway.php
Resolves error on attempt at checkout with the redirect flow, where no order is seemingly created/updated in the process. Does seem to solve the issue, but should perhaps be fixed in a different way?
=> Create order in redirect flow
